disabled_rules:
- trailing_whitespace
opt_in_rules:
- empty_count
- empty_string
excluded:
- Carthage
- Pods
line_length:
    warning: 300
    error: 350
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true
function_body_length:
    warning: 300
    error: 500
function_parameter_count:
    warning: 6
    error: 8
type_body_length:
    warning: 300
    error: 500
file_length:
    warning: 1000
    error: 1500
    ignore_comment_only_lines: true
identifier_name:
  min_length: 1 # only min_length
  excluded: # excluded via string array
    - T
    - id
    - URL
    - Error
    - Success
cyclomatic_complexity:
    warning: 15
    error: 25
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
reporter: "xcode"
